import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const docsDir = path.resolve(__dirname, '../src/content/docs');

function getMdxFiles(dir, fileList = []) {
  if (!fs.existsSync(dir)) return fileList;
  const files = fs.readdirSync(dir);
  for (const file of files) {
    const filePath = path.join(dir, file);
    if (fs.statSync(filePath).isDirectory()) {
      getMdxFiles(filePath, fileList);
    } else if (filePath.endsWith('.mdx') || filePath.endsWith('.md')) {
      fileList.push(filePath);
    }
  }
  return fileList;
}

function countVerses(filePath, tag) {
  const content = fs.readFileSync(filePath, 'utf8');
  const matches = content.match(new RegExp(tag, 'gi'));
  return matches ? matches.length : 0;
}

// Collections to analyze
const poetryCollections = [
  { id: 'haikus', name: 'Haikus', tag: '<Limerick', cromulentCount: 5 },
  { id: 'limericks', name: 'Limericks', tag: '<Limerick', cromulentCount: 10 },
  { id: 'aphorisms', name: 'Aphorisms', tag: '<Broside', cromulentCount: 8 }
];

const targetCollections = [
  { id: 'lorelog', name: 'Lorelog' },
  { id: 'mascots', name: 'Mascots' },
  { id: 'reference', name: 'Reference' },
  { id: 'posts', name: 'Posts' }
];

const data = {};

// 1. Gather poetry files and verse counts
poetryCollections.forEach(p => {
  const pDir = path.join(docsDir, p.id);
  const files = getMdxFiles(pDir);
  let totalVerses = 0;
  const fileStats = [];
  files.forEach(f => {
    const count = countVerses(f, p.tag);
    totalVerses += count;
    fileStats.push({ file: path.basename(f), count });
  });
  fileStats.sort((a, b) => b.count - a.count); // desc
  
  data[p.id] = {
    files: fileStats,
    totalFiles: files.length,
    totalVerses,
    cromulentCount: p.cromulentCount
  };
});

// 2. Gather coverage matrix
const coverage = {};
targetCollections.forEach(t => {
  const tDir = path.join(docsDir, t.id);
  const files = getMdxFiles(tDir);
  let cov = { haikus: 0, limericks: 0, aphorisms: 0, total: files.length };
  
  const clean = str => str.replace(/[-_.]/g, '').toLowerCase();
  
  files.forEach(f => {
    const base = clean(path.basename(f, path.extname(f)));
    if (data.haikus.files.some(hf => clean(hf.file).includes(base))) cov.haikus++;
    if (data.limericks.files.some(lf => clean(lf.file).includes(base))) cov.limericks++;
    if (data.aphorisms.files.some(af => clean(af.file).includes(base))) cov.aphorisms++;
  });
  
  coverage[t.id] = cov;
});

// 3. Generate Markdown
let md = `---
title: "Poetry Audit Report"
slug: reference/fref-0900-poet
description: "Automatically generated dashboard detailing the coverage of our poetry collections."
date: ${new Date().toISOString().split('T')[0]}
versionLabel: shelf-note
status: archived
classification: internal
caseNumber: FREF-0900-POET
tags:
  - reference
  - audit
  - poetry
  - density
tableOfContents: true
updatedAt: ${new Date().toISOString().split('T')[0]}
---

# Poetry Collection Audit Dashboard

This report is automatically generated by \`scripts/audit-poetry.mjs\`. It details the coverage and total verse counts of all poetry collections across the archival silos.

## Archive Totals

| Collection | Total Files | Total Verses |
|------------|-------------|--------------|
`;

poetryCollections.forEach(p => {
  md += `| **${p.name}** | ${data[p.id].totalFiles} | ${data[p.id].totalVerses} |\n`;
});

md += `\n## Coverage Matrix\n\n`;

targetCollections.forEach(t => {
  const c = coverage[t.id];
  md += `### ${t.name} (${c.total} total records)\n\n`;
  md += `| Poetry | Coverage | Missing Files |\n`;
  md += `|--------|----------|---------------|\n`;
  poetryCollections.forEach(p => {
    const covered = c[p.id];
    const missing = c.total - covered;
    const pct = c.total === 0 ? 100 : Math.round((covered / c.total) * 100);
    const bars = '▓'.repeat(Math.round(pct / 10));
    md += `| ${p.name} | ${bars} ${pct}% | ${missing} |\n`;
  });
  md += `\n`;
});

md += `## Density Extremes

This section highlights the most and least densely populated poetry files across the archive. This allows us to identify records with an over-abundance of verses, and those struggling to maintain archival weight.
`;

poetryCollections.forEach(p => {
  md += `\n### ${p.name} Density\n\n`;
  md += `**Top 10 Most Verses**\n\n| File | Verses |\n|------|--------|\n`;
  const top10 = data[p.id].files.slice(0, 10);
  top10.forEach(f => {
    md += `| \`${f.file}\` | ${f.count} |\n`;
  });
  
  md += `\n**The Cromulent Seven**\n\n| File | Verses |\n|------|--------|\n`;
  const cromulent = data[p.id].files.filter(f => f.count === data[p.id].cromulentCount).slice(0, 7);
  cromulent.forEach(f => {
    md += `| \`${f.file}\` | ${f.count} |\n`;
  });
  
  md += `\n**Bottom 10 Least Verses**\n\n| File | Verses |\n|------|--------|\n`;
  const bottom10 = data[p.id].files.slice(-10).reverse();
  bottom10.forEach(f => {
    md += `| \`${f.file}\` | ${f.count} |\n`;
  });
});

const reportPath = path.join(docsDir, 'reference/fref-0900-poet.mdx');
fs.writeFileSync(reportPath, md, 'utf8');
console.log(`Generated FREF report at ${reportPath}`);

// We also need to keep the original sidecar missing files check since it existed
const sidecarDir = path.resolve(__dirname, '../src/data/sidecar');
const allMdxFilesFullPaths = getMdxFiles(docsDir);
const allMdxFiles = allMdxFilesFullPaths.map(f => path.relative(path.resolve(__dirname, '..'), f).replace(/\\/g, '/'));

function getJsonFiles(dir) {
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir).filter(f => f.endsWith('.json')).map(f => path.join(dir, f));
}

let processedMdxFiles = new Set();
getJsonFiles(sidecarDir).forEach(sidecarFile => {
  try {
    const data = JSON.parse(fs.readFileSync(sidecarFile, 'utf-8'));
    if (data.records) data.records.forEach(r => { if (r.file_path) processedMdxFiles.add(r.file_path); });
  } catch(e){}
});

const unmappedFiles = allMdxFiles.filter(file => !processedMdxFiles.has(file));
if (unmappedFiles.length > 0) {
  console.log(`Found ${unmappedFiles.length} unmapped .mdx files that need poetry...`);
  const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
  const newBatchFile = path.join(sidecarDir, `batch_${timestamp}.json`);
  const batchData = {
    batch_timestamp: new Date().toISOString(),
    total_files_processed: unmappedFiles.length,
    records: unmappedFiles.map(f => ({ file_path: f, verses: [] }))
  };
  fs.writeFileSync(newBatchFile, JSON.stringify(batchData, null, 2));
  console.log(`Auto-scaffolded placeholders in ${newBatchFile}`);
} else {
  console.log("All .mdx files are mapped. No unmapped files found.");
}
